language: cpp

# os:
  # - windows
  # - linux
  # - osx

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - PLATFORM_NAME="linux"
    - os: osx
      osx_image: xcode11.1
      compiler: clang
      env:
        - PLATFORM_NAME="darwin"
    - os: windows

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then eval "${MATRIX_EVAL}"; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then chmod +x ./build.sh; fi
script:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./build.bat; else ./build.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./build/win/x64/Release/toyotest.exe; else ./build/"$PLATFORM_NAME"/Release/toyotest; fi
